// lib/portfolio/mockPortfolioData.ts
// Realistic mock portfolio profiles for development and demos.
// To connect a real database:
//   1. Replace getPortfolioUser() in services/portfolioService.ts
//   2. Keep this file as a fallback for seeding / Storybook / tests.

import { PortfolioUser } from '@/lib/types'

export const MOCK_PORTFOLIO_USERS: Record<string, PortfolioUser> = {
  'user-arjun': {
    uid: 'user-arjun',
    name: 'Arjun Mehta',
    username: 'arjunm',
    bio: 'Full-stack developer obsessed with shipping fast. Won KHOJ Web Dev Championship S2. Building products that outlast the hype cycle.',
    field: 'Coding',
    availableForOpportunities: true,
    contactEmail: 'arjun@example.com',
    location: 'Kathmandu, Nepal',
    country: 'Nepal',
    verifiedChampion: true,
    xp: 2340,
    rank: 3,
    wins: 7,
    matchesPlayed: 12,
    skills: ['React', 'Next.js', 'TypeScript', 'Node.js', 'PostgreSQL', 'Docker'],
    createdAt: new Date(Date.now() - 210 * 24 * 60 * 60 * 1000).toISOString(),
    achievements: [
      {
        id: 'a1',
        title: 'Web Dev Champion S2',
        description: 'First place in KHOJ Web Dev Championship Season 2 out of 148 competitors.',
        date: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
        icon: '🏆',
        xpValue: 500,
      },
      {
        id: 'a2',
        title: '90-Day Streak',
        description: 'Coded every day for 90 consecutive days and shared progress publicly.',
        date: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
        icon: '🔥',
        xpValue: 200,
      },
      {
        id: 'a3',
        title: 'Top 10 National Rank',
        description: 'Broke into the national top 10 ranking on KHOJ leaderboard.',
        date: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
        icon: '◈',
        xpValue: 150,
      },
    ],
    projects: [
      {
        id: 'p1',
        title: 'KHOJ Tracker CLI',
        description: 'Command-line tool to track your KHOJ XP, ranking, and tournament schedule from the terminal.',
        techStack: ['Node.js', 'TypeScript', 'Ink'],
        repoUrl: 'https://github.com/arjunm/khoj-tracker',
        builtAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
        featured: true,
      },
      {
        id: 'p2',
        title: 'DevBoard',
        description: 'Real-time collaborative coding dashboard built for remote pair programming sessions.',
        techStack: ['Next.js', 'Socket.io', 'Monaco Editor', 'Redis'],
        liveUrl: 'https://devboard.demo',
        repoUrl: 'https://github.com/arjunm/devboard',
        builtAt: new Date(Date.now() - 75 * 24 * 60 * 60 * 1000).toISOString(),
      },
    ],
    competitions: [
      {
        id: 'c1',
        tournamentId: 'tourn-webdev-s2',
        tournamentTitle: 'Web Dev Championship Season 2',
        category: 'Coding',
        placement: '1st',
        xpEarned: 500,
        date: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
        prize: 5000,
      },
      {
        id: 'c2',
        tournamentId: 'tourn-algo-s1',
        tournamentTitle: 'Algorithm Blitz Season 1',
        category: 'Coding',
        placement: 'top10',
        xpEarned: 180,
        date: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
      },
    ],
    socialLinks: {
      github: 'https://github.com/arjunm',
      linkedin: 'https://linkedin.com/in/arjunm',
      twitter: 'https://twitter.com/arjunm_dev',
    },
  },

  'user-priya': {
    uid: 'user-priya',
    name: 'Priya Sharma',
    username: 'priyas',
    bio: 'Designer turned full-stack dev. First $1000 freelance win through KHOJ. Building tools that make complex things simple.',
    field: 'Design',
    availableForOpportunities: false,
    location: 'Mumbai, India',
    country: 'India',
    verifiedChampion: false,
    xp: 1890,
    rank: 8,
    wins: 4,
    matchesPlayed: 9,
    skills: ['Figma', 'React', 'Tailwind CSS', 'UI/UX', 'Framer Motion', 'Next.js'],
    createdAt: new Date(Date.now() - 180 * 24 * 60 * 60 * 1000).toISOString(),
    achievements: [
      {
        id: 'a1',
        title: 'First Freelance Win',
        description: 'Landed first $1000 freelance project directly through KHOJ community.',
        date: new Date(Date.now() - 40 * 24 * 60 * 60 * 1000).toISOString(),
        icon: '💰',
        xpValue: 300,
      },
      {
        id: 'a2',
        title: 'UI Design Runner-Up',
        description: '2nd place in KHOJ UI Showdown — judged on creativity, accessibility, and speed.',
        date: new Date(Date.now() - 70 * 24 * 60 * 60 * 1000).toISOString(),
        icon: '🥈',
        xpValue: 220,
      },
    ],
    projects: [
      {
        id: 'p1',
        title: 'DesignSprint Kit',
        description: 'Free Figma template system for product teams running 5-day design sprints. 2k+ downloads.',
        techStack: ['Figma', 'FigJam'],
        liveUrl: 'https://figma.com/@priyas/design-sprint-kit',
        builtAt: new Date(Date.now() - 55 * 24 * 60 * 60 * 1000).toISOString(),
        featured: true,
      },
    ],
    competitions: [
      {
        id: 'c1',
        tournamentId: 'tourn-ui-s1',
        tournamentTitle: 'UI Design Showdown Season 1',
        category: 'Design',
        placement: '2nd',
        xpEarned: 300,
        date: new Date(Date.now() - 70 * 24 * 60 * 60 * 1000).toISOString(),
        prize: 2500,
      },
    ],
    socialLinks: {
      linkedin: 'https://linkedin.com/in/priyas',
      website: 'https://priyas.design',
      instagram: 'https://instagram.com/priyas.design',
    },
  },

  'user-rishi': {
    uid: 'user-rishi',
    name: 'Rishi Nair',
    username: 'rishin',
    bio: 'DSA grinder. 90-day public build streak. Making algorithms feel less scary through visualizations.',
    field: 'Coding',
    availableForOpportunities: true,
    location: 'Pokhara, Nepal',
    country: 'Nepal',
    verifiedChampion: false,
    xp: 560,
    rank: 42,
    wins: 1,
    matchesPlayed: 5,
    skills: ['Python', 'C++', 'DSA', 'System Design', 'Machine Learning'],
    createdAt: new Date(Date.now() - 95 * 24 * 60 * 60 * 1000).toISOString(),
    achievements: [
      {
        id: 'a1',
        title: '90-Day Build Streak',
        description: 'Built and shipped daily for 90 days. All shared in the KHOJ community.',
        date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        icon: '⚡',
        xpValue: 200,
      },
    ],
    projects: [
      {
        id: 'p1',
        title: 'AlgoViz',
        description: 'Interactive algorithm visualizer — watch sorting, graph traversal, and DP in real-time.',
        techStack: ['React', 'D3.js', 'TypeScript'],
        liveUrl: 'https://algoviz.demo',
        repoUrl: 'https://github.com/rishin/algoviz',
        builtAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
        featured: true,
      },
    ],
    competitions: [
      {
        id: 'c1',
        tournamentId: 'tourn-algo-s1',
        tournamentTitle: 'Algorithm Blitz Season 1',
        category: 'Coding',
        placement: 'finalist',
        xpEarned: 120,
        date: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
      },
    ],
    socialLinks: {
      github: 'https://github.com/rishin',
      twitter: 'https://twitter.com/rishin_builds',
    },
  },

  'user-karan': {
    uid: 'user-karan',
    name: 'Karan Bajaj',
    username: 'karanb',
    bio: 'Startup founder in the making. Won a hackathon with 3 strangers I met in this community. Now we are building together.',
    field: 'Startups',
    availableForOpportunities: true,
    contactEmail: 'karan@example.com',
    location: 'Bangalore, India',
    country: 'India',
    verifiedChampion: true,
    xp: 780,
    rank: 28,
    wins: 2,
    matchesPlayed: 6,
    skills: ['Product Management', 'React', 'Go', 'Startup Strategy', 'Pitch Decks'],
    createdAt: new Date(Date.now() - 140 * 24 * 60 * 60 * 1000).toISOString(),
    achievements: [
      {
        id: 'a1',
        title: 'Hackathon Winner',
        description: 'Won KHOJ Startup Weekend hackathon with a team of 4 strangers from the community.',
        date: new Date(Date.now() - 50 * 24 * 60 * 60 * 1000).toISOString(),
        icon: '🏆',
        xpValue: 350,
      },
    ],
    projects: [
      {
        id: 'p1',
        title: 'TeamUp.so',
        description: 'Platform to find co-founders and collaborators for startup ideas — born from the KHOJ hackathon win.',
        techStack: ['Next.js', 'Supabase', 'TypeScript', 'Tailwind'],
        liveUrl: 'https://teamup.so',
        builtAt: new Date(Date.now() - 35 * 24 * 60 * 60 * 1000).toISOString(),
        featured: true,
      },
    ],
    competitions: [
      {
        id: 'c1',
        tournamentId: 'tourn-startup-s1',
        tournamentTitle: 'Startup Weekend Season 1',
        category: 'Startups',
        placement: '1st',
        xpEarned: 350,
        date: new Date(Date.now() - 50 * 24 * 60 * 60 * 1000).toISOString(),
        prize: 10000,
      },
    ],
    socialLinks: {
      linkedin: 'https://linkedin.com/in/karanb',
      twitter: 'https://twitter.com/karanb_builds',
      website: 'https://teamup.so',
    },
  },

  'user-meena': {
    uid: 'user-meena',
    name: 'Meena Karki',
    username: 'meenak',
    bio: 'Rejected 12 times. Ranked #7 nationally. Resilience is the real skill. Helping others navigate the grind.',
    field: 'Career',
    availableForOpportunities: false,
    location: 'Lalitpur, Nepal',
    country: 'Nepal',
    verifiedChampion: true,
    xp: 1440,
    rank: 7,
    wins: 5,
    matchesPlayed: 10,
    skills: ['Career Coaching', 'React', 'Node.js', 'Interview Prep', 'Technical Writing'],
    createdAt: new Date(Date.now() - 300 * 24 * 60 * 60 * 1000).toISOString(),
    achievements: [
      {
        id: 'a1',
        title: 'National Rank #7',
        description: 'Achieved top 10 national rank on KHOJ after months of consistent improvement.',
        date: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
        icon: '◈',
        xpValue: 400,
      },
      {
        id: 'a2',
        title: 'Community Mentor Badge',
        description: 'Awarded for helping 50+ community members with interview prep and career advice.',
        date: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
        icon: '🌟',
        xpValue: 150,
      },
    ],
    projects: [],
    competitions: [
      {
        id: 'c1',
        tournamentId: 'tourn-career-s1',
        tournamentTitle: 'Career Sprint Season 1',
        category: 'Career',
        placement: '1st',
        xpEarned: 400,
        date: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
        prize: 3000,
      },
      {
        id: 'c2',
        tournamentId: 'tourn-career-s0',
        tournamentTitle: 'Career Sprint Season 0',
        category: 'Career',
        placement: '3rd',
        xpEarned: 200,
        date: new Date(Date.now() - 120 * 24 * 60 * 60 * 1000).toISOString(),
      },
    ],
    socialLinks: {
      linkedin: 'https://linkedin.com/in/meenak',
      twitter: 'https://twitter.com/meenak_career',
    },
  },
}

/** Fallback for any uid not in the mock map */
export function getMockPortfolioUser(uid: string): PortfolioUser | null {
  return MOCK_PORTFOLIO_USERS[uid] ?? null
}
